### ISSUE TITLE
Crockfords standards not entirely compatible with Optus?

### ISSUE THREAD

**Issue by ScottMaclure** [optus-dev/Optus-Best-Practices#1]
1) "Do not use $ (dollar sign) or \ (backslash) in names."

We use the dollar sign for variables representing jQuery wrapped DOM elements.

2) I want to confirm that the 80 character limit is only a guideline, and doesn't need to be strictly enforced?

Crockford states that when breaking a line @ 80 characters, the next line should be indented 8 spaces. Why not just 4?

3) With comments, do we want to recommend the syntax required for a doc generator program, and if so, which one? I.e:

http://stackoverflow.com/questions/4498213/jquery-compatible-javascript-documentation-generator

Do we also want to include JS documentation generation as part of our workflow (grunt task)?

4) Rather than declaring variables in alphabetical order, I often find it more useful to group them by how they relate to each other.

5) By "implied global variables should never be used", does that imply we'll be wrapping all JS in closures, and passing globals (like jQuery, Backbone, etc) in? That also means JSHint comments.

6) Crockford tends to "un-dent" comments inside a function. I prefer to have them matching the indentation of the code around them. See his "getElementsByClassName" example.

7) Crockford's not explicit, but I assume we'll use camelCasing over snake_casing for function/variable names?

8) We generally don't bother with private members. Any opinion on promoting that (or not)?

9) Note that jQuery/Underscore have altenatives for the "for (variable in object) {" syntax. Perhaps promote usage of these generic iterator functions, as they can be used for objects and arrays.

**Comment by blakehaswell** [comment]
I agree for the most part and will update the document as required.
1.  Agree.
2.  80 char limit is pretty irrelevant these days. I’m happy for us to ignore it.
   
   As for indentation, take the following example:
   
   ```
   if (someReallyLongFunctionName() === "A really long string"
           && someOtherCondition === otherConditionExpectedValue) {
       doStuff();
   }
   ```
   
   If we only indented the second line 4 chars, then it is harder to parse where the condition ends and where the block starts.
3.  Yes and yes. I have no opinion on which JSDoc generator to use.
4.  Agree.
5.  No, this just means that we will not do `variable = "value";` if `variable` has not been previously defined. Any undefined variable that has a value assigned to it is an implied global. This is confusing behaviour and we must avoid code which triggers it.
6.  Agree, I find that convention stupid. I don’t think that convention is documented anywhere though, so I don’t know that we need to say anything.
7.  Correct.
8.  No opinion. Feel free to argue for/against it if you do. :-)
9.  Agree. The `for (variable in object)` syntax is a “bad part”. ;-)

**Comment by PascalZajac** [comment]
Agree with Blake with the following exceptions/expansions:

#5. Wrapping stuff in closures does nothing that we don't already get by running JSHint and paying attention to use of undeclared variables. We also won't be bothering with "use strict" for the same reason - all it does is provide warnings that JSHint gives us, and offers no performance benefit.

#8. Private members in a language without visibility = stupid. The only plausible reason is if you really, really need to ensure a value takes a particular format. It implies you don't trust your developers to use the documented setter method that exists (in which case, fire them). As you move to things like Backbone where you can specify validators for models, it becomes even less necessary.

#9. So what are we advocating? arr.each(function(arrItem){}) works for arrays but what do we prescribe for objects? jQuery.each?

**Comment by blakehaswell** [comment]
For #9, we should use `$.each` or `_.each`.

I would argue that we should use the jQuery flavour where possible so that we’re not tied to backbone/underscore, however jQuery is a DOM manipulation library and it could be argued that jQuery code should only be present in views (but I don’t think that argument is particularly strong for convenience methods).

**Comment by ScottMaclure** [comment]
Q: Does "use strict" incur a performance penalty? My editor (sublimetext) makes use of "use strict" for its inline linting (there's probably a global option to turn that on). Just FYI.

The linter program:
https://github.com/SublimeLinter/SublimeLinter

Edit: Yes I can with jshint_options (as per http://www.jshint.com/docs/).

**Comment by blakehaswell** [comment]
`"use strict"` has no penalty nor benefit for performance AFAIK.

As Pas mentioned, we won’t be implementing it because linting provides all the benefits strict mode would and more.

**Comment by ScottMaclure** [comment]
So, something like this for jshint options (gruntfile.js)?

https://gist.github.com/2595796

Edit: my current options in my branch's gruntfile.js AND my linter config for my editor:

"bitwise"       : true,     // Prohibit bitwise operators (&, |, ^, etc.).
"curly"         : true,     // Require {} for every new block or scope.
"eqeqeq"        : true,     // Require triple equals i.e. `===`.
"forin"         : true,     // Tolerate `for in` loops without `hasOwnPrototype`.
"immed"         : true,     // Require immediate invocations to be wrapped in parens e.g. `( function(){}() );`
"latedef"       : true,     // Prohibit variable use before definition.
"newcap"        : true,     // Require capitalization of all constructor functions e.g. `new F()`.
"noarg"         : true,     // Prohibit use of `arguments.caller` and `arguments.callee`.
"noempty"       : true,     // Prohibit use of empty blocks.
"nonew"         : true,     // Prohibit use of constructors for side-effects.
"plusplus"      : true,     // Prohibit use of `++` & `--`.
"regexp"        : true,     // Prohibit `.` and `[^...]` in regular expressions.
"undef"         : true,     // Require all non-global variables be declared before they are used.
//"strict"        : true,     // Require `use strict` pragma in every file.
"trailing"      : true,     // Prohibit trailing whitespaces.
"browser"       : true,     // Standard browser globals e.g. `window`, `document`.
"indent"        : 4         // Specify indentation spacing

**Comment by blakehaswell** [comment]
I’ve updated the doc to include the exceptions and additions we have discussed here.
