### ISSUE TITLE
Jasmine spec filename

### ISSUE THREAD

**Issue by ScottMaclure** [optus-dev/Optus-Best-Practices#2]
Not really an issue, but I can see:

"Specs should be saved with the .spec.js extension."

Note that currently, all spec filenames are "myPluginSpec.js", where "myPlugin.js" is the original plugin name (and the constructor function is MyPlugin).

Happy to make that the standard? Not fussed really.

**Comment by blakehaswell** [comment]
I think it was @PascalZajac who suggested this convention. I believe it is widely used across open source projects he’d seen, so that’s why we adopted it.

**Comment by PascalZajac** [comment]
Jasmine-node expects all test files to end in .spec.js so it knows which files to load into the test runner it automatically generates. It seemed like a decent pattern to follow. One of the Grunt Jasmine plugins stipulates the same thing.

It's probably more visually apparent how related the two files are using myPlugin.js and myPlugin.spec.js too.

**Comment by blakehaswell** [comment]
Ok, `.spec.js` it is.
